name: Deploy staging

on:
  workflow_run:
    workflows: ['Check code']
    types:
      - completed
    branches:
      - main

jobs:
  deploy-staging:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: ‚¨áÔ∏è Checkout code
        uses: actions/checkout@v4

      - name: ü§ì Read .nvmrc
        id: nvm
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: üê≥ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: üîê Log in to Private Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

      # WEBSITE
      - name: üì¶ Metadata for Website Docker image
        id: meta_website
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.PRIVATE_REGISTRY_URL }}/${{ github.repository_owner }}/${{ github.event.repository.name }}-website-staging
          tags: |
            type=raw,value=latest
          labels: |
            org.opencontainers.image.version=staging
            org.opencontainers.image.source=${{ github.repositoryUrl }}

      - name: üèóÔ∏è Build & Push Website Docker image
        uses: docker/build-push-action@v5
        with:
          target: website-distroless
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta_website.outputs.tags }}
          labels: ${{ steps.meta_website.outputs.labels }}
          build-args: |
            NODE_VERSION=${{ steps.nvm.outputs.NODE_VERSION }}

      # CMS
      - name: üì¶ Metadata for CMS Docker image
        id: meta_cms
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.PRIVATE_REGISTRY_URL }}/${{ github.repository_owner }}/${{ github.event.repository.name }}-cms-staging
          tags: |
            type=raw,value=latest
          labels: |
            org.opencontainers.image.version=staging
            org.opencontainers.image.source=${{ github.repositoryUrl }}

      - name: üèóÔ∏è Build & Push Website Docker image
        uses: docker/build-push-action@v5
        with:
          target: cms-distroless
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta_website.outputs.tags }}
          labels: ${{ steps.meta_website.outputs.labels }}
          build-args: |
            NODE_VERSION=${{ steps.nvm.outputs.NODE_VERSION }}
